### ISSUE TITLE
有没有办法在某一样式停用 flexboxfixer

### ISSUE THREAD

**Issue by daqi** [huixisheng/fis3-postprocessor-autoprefixer#3]
`-webkit-line-clamp:2`必须结合`display:-webkit-box`使用
加入`/*autoprefixer: off*/`之后，还会出现 `display:flex`,导致样式覆盖

**Comment by huixisheng** [comment]
@daqi 
目前我采取的办法是对相应的css不做`postprocessor`

```
fis.match('/css/util/nowrap.css', {
  useMap: false,
  postprocessor: null
});
```

**Comment by daqi** [comment]
感觉也就只有这个方法了
