### ISSUE TITLE
不支持 last major versions的query

### ISSUE THREAD

**Issue by yaoweiprc** [huixisheng/fis3-postprocessor-autoprefixer#4]
browsers参数使用了‘last 2 iOS major versions’来控制支持最新的两个ios大版本，这个写法是browserslist文档里支持的写法，但是构建的时候报下面的错误：
[ERROR] postprocessor.autoprefixer: Unknown browser query `last 2 iOS major versions` [C:/Users/yaowei02/Desktop/wise/src/translation-mobile/static/base/normalize.css] in [/static/base/base.css]

**Comment by huixisheng** [comment]
升级了依赖，已支持
